/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CollegeId = IDL.Nat;
export const College = IDL.Record({
  'id' : CollegeId,
  'courses' : IDL.Vec(IDL.Text),
  'fees' : IDL.Nat,
  'name' : IDL.Text,
  'type' : IDL.Text,
  'established' : IDL.Nat,
  'description' : IDL.Text,
  'rating' : IDL.Float64,
  'placement_percentage' : IDL.Float64,
  'location' : IDL.Text,
});
export const CollegeFilter = IDL.Record({
  'minFees' : IDL.Opt(IDL.Nat),
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'search' : IDL.Opt(IDL.Text),
  'maxFees' : IDL.Opt(IDL.Nat),
  'location' : IDL.Opt(IDL.Text),
});
export const PagedColleges = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'colleges' : IDL.Vec(College),
});

export const idlService = IDL.Service({
  'getCollege' : IDL.Func([IDL.Nat], [IDL.Opt(College)], ['query']),
  'getColleges' : IDL.Func([CollegeFilter], [PagedColleges], ['query']),
  'getLocations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSavedColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
  'saveCollege' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unsaveCollege' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CollegeId = IDL.Nat;
  const College = IDL.Record({
    'id' : CollegeId,
    'courses' : IDL.Vec(IDL.Text),
    'fees' : IDL.Nat,
    'name' : IDL.Text,
    'type' : IDL.Text,
    'established' : IDL.Nat,
    'description' : IDL.Text,
    'rating' : IDL.Float64,
    'placement_percentage' : IDL.Float64,
    'location' : IDL.Text,
  });
  const CollegeFilter = IDL.Record({
    'minFees' : IDL.Opt(IDL.Nat),
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'search' : IDL.Opt(IDL.Text),
    'maxFees' : IDL.Opt(IDL.Nat),
    'location' : IDL.Opt(IDL.Text),
  });
  const PagedColleges = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'colleges' : IDL.Vec(College),
  });
  
  return IDL.Service({
    'getCollege' : IDL.Func([IDL.Nat], [IDL.Opt(College)], ['query']),
    'getColleges' : IDL.Func([CollegeFilter], [PagedColleges], ['query']),
    'getLocations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSavedColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
    'saveCollege' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unsaveCollege' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };